### ISSUE TITLE
css

### ISSUE THREAD

**Issue by AkashDev23** [harsh98trivedi/Simple-JavaScript-Calculator#10]
It would be better if the users would be able to see the cursor. And also the button press when pressing the button from keyboard.

**Comment by SavainB** [comment]
can i do that for you ?

**Comment by harsh98trivedi** [comment]
Sure, @SavainB! I have assigned the issue to you.

**Comment by RuneBlast** [comment]
Hello, I forgot to send a message here. I'm working with SavainB, can i be assigned to this issue too please ?

**Comment by harsh98trivedi** [comment]
Sure, @RuneBlast!
