### ISSUE TITLE
Isuue with javascript part.

### ISSUE THREAD

**Issue by rohitLovesKrishna** [harsh98trivedi/Simple-JavaScript-Calculator#11]
After equals calculator is supposed to clear the result from the screen with new key press. But, unforu. your program is adding that to the previous numbers.

**Comment by HrutikaBadgeri** [comment]
Hey, I have worked on this issue and resolved it. Please assign me this issue, I'll send a pull request tomorrow, do review it :)

**Comment by harsh98trivedi** [comment]
@HrutikaBadgeri, I have assigned the issue to you!
