### ISSUE TITLE
missing button!

### ISSUE THREAD

**Issue by Yash636261** [harsh98trivedi/Simple-JavaScript-Calculator#16]
A simple clear entry (CE) button would be nice addition which can delete last entry in calculator.

**Comment by Mohamedhazeem** [comment]
I changed this project by remove brackets then add backspace and double zero button if you want check this out - https://github.com/Mohamedhazeem/Simple_Calculator.git

If we need to add backspace, we'll remove some buttons in this calculator.

**Comment by Akshat162001** [comment]
can u assign it to me ..
so that i can work for it

**Comment by harsh98trivedi** [comment]
Sure @Akshat162001, assigning it to you!

**Comment by Akshat162001** [comment]
Done Completed by @Akshat162001

**Comment by Akshat162001** [comment]
I literally enjoyed your way of writing js code...
