### ISSUE TITLE
Arithmetic operator multiple print

### ISSUE THREAD

**Issue by sherawat-Lokesh** [harsh98trivedi/Simple-JavaScript-Calculator#17]
`+,-,*,/ ` are getting printed multiple times
<img width="1440" alt="Screenshot 2023-02-09 at 08 00 29" src="https://user-images.githubusercontent.com/107927380/217867963-eee0398f-47bb-4e8d-879c-0c82dacca8db.png">

**Comment by LeonardoHobeni** [comment]
So you want the program to know when not to print another operator before printing a number?
