### ISSUE TITLE
visibility

### ISSUE THREAD

**Issue by CyCodez** [harsh98trivedi/Simple-JavaScript-Calculator#18]
when value is less than zero, should show a red color, and green otherwise
can you assigned this to me thanks

**Comment by harsh98trivedi** [comment]
Assigned to you @CyCodez

**Comment by Akshat162001** [comment]
harsh i am interested to solve this problem but not able decode his statement show red color where ??

**Comment by CyCodez** [comment]
i mean the color of the number itself when it is less than zero-"red" and "green" when it is greater than zero

**Comment by Akshat162001** [comment]
Okay Okay..Understood

**Comment by Akshat162001** [comment]
I am also working on it..on this issue...

**Comment by Akshat162001** [comment]
Tried to solve the issue....

**Comment by sohaildotcss** [comment]
is this issue resolved now or is it still open.?

**Comment by harsh98trivedi** [comment]
@sohaildotcss, it is still open

**Comment by sarthaksharma27** [comment]
@harsh98trivedi I just made a pull request regarding a change please verify it.
