### ISSUE TITLE
can i add light mode and dark mode toggle functionality ?

### ISSUE THREAD

**Issue by Siddheshjondhale** [harsh98trivedi/Simple-JavaScript-Calculator#20]
Please assign me this issue so i can contribute

**Comment by Mudit-Jxin7** [comment]
hey @Siddhesh172004  If you are not working on it , can I?

**Comment by harsh98trivedi** [comment]
Sure @Mudit-Jxin7, let me assign you the issue!

**Comment by harsh98trivedi** [comment]
Thanks to @SuryakantM24 for creating a PR for this issue!
