### ISSUE TITLE
Failure to input opening parentheses.

### ISSUE THREAD

**Issue by ghost** [harsh98trivedi/Simple-JavaScript-Calculator#29]
If you try to input a "(" first in the calculator, it fails and doesn't show. This case is also for the closing parentheses

**Comment by shail-patel-321** [comment]
can you assign this issue to me

**Comment by ghost** [comment]
@PlasticPath I am not the owner of the repository, I just found the issue. We might have to wait for the owner

**Comment by harsh98trivedi** [comment]
Assigned to you @PlasticPath
